services:
  galaxy:
    image: ghcr.io/octopyid/galaxy:latest
    container_name: galaxy
    restart: unless-stopped
    ports:
      - "1337:1337"
    environment:
      - PORT=1337
    volumes:
      - galaxy:/app/data

volumes:
  galaxy:
